In [1]:
import numpy as np

In [2]:
def takeInput(filename):
    """
    ### Description:
    Takes the input from filename, reads the number of nodes and number edges, initializes te adjacency matrix of order n*n, and assigns value to 1 for pair of nodes which have directed edge.

    ### Args:
    `filename` : The name of the file from which we will take the required input.

    ### Returns:
    `arr` : The adjacency matrix.

    `n` : The number of nodes.
    """
    file = open(filename,'r')
    n = int(file.readline().strip())
    e = int(file.readline().strip())
    arr = np.zeros((n,n))
    for i in range(e):
        line = file.readline()
        edge = line.strip().split()
        arr[int(edge[0]) - 1][int(edge[1]) - 1] = 1
    return arr, n

In [3]:
def createProbabilityMatrix(arr, n, alpha, teleport):
    """
    ### Description:
    Creates the probability matrix.

    ### Args:
    `arr` : The adjacency matrix.

    `n` : The number of nodes.

    `alpha` : probability of teleportation if its allowed.

    `teleport` : The boolean value whether teleportation is allowed or not.

    ### Returns:
    returns the probability matrix.
    """
    if(not teleport):
        alpha=0
    rowsums = np.sum(arr, axis = 1)
    prob = np.zeros((n,n))
    for i in range(n):
        if (rowsums[i] == 0):
            prob[i] = (1.0/n) if teleport else 0
        else:
            prob[i] = arr[i]/rowsums[i]
            prob[i] = prob[i]*(1 - alpha) 
            prob[i] = prob[i] + (alpha/n)   #(1 if rowsums[i] == 0 else rowsums[i])
    return prob

In [4]:
def power_iteration(prob, n):
    """
    ### Description:
    Implementation of PageRank algorithm using power iteration method.

    ### Args:
    `prob` : The probability matrix.

    `n` : The number of nodes.

    ### Returns:
    Doesn't returns anything, but prints the desired output.
    """
    old = np.zeros((1,n))
    old[0][2] = 1.0
    new = old@prob
    diff = np.abs(new - old)
    while (np.sum(diff) > 0.00000001):
        temp = new@prob
        old = new
        new = temp
        diff = np.abs(old - new)
    print("PageRank scores using power iteration: ", new)
    print("Descending order of nodes by PageRank:")
    print((np.flip(np.argsort(new[0]))+1))


In [5]:
def rankAndSort(prob, n):
    """
    ### Description:
    Implementation of PageRank algorithm using linear algebra packages.

    ### Args:
    `prob` : The probability matrix.

    `n` : The number of nodes.

    ### Returns:
    Doesn't returns anything, but prints the desired output.
    """
    v, V = np.linalg.eig(prob.T)
    for i in range(v.size):
        if (np.abs(v[i] - 1.0000) < 0.0000001):
            index = i
    leftvec = V[:,index].T
    ans = leftvec/np.sum(leftvec)
    print("PageRank scores using linear algebra packages: ", ans)
    print("Descending order of nodes by PageRank:")
    print((np.flip(np.argsort(ans))+1))
    evalues = np.abs(v)
    indices = np.argsort(evalues)
    if(evalues.size == 1 or evalues[indices[-1]] - evalues[indices[-2]] > 0.00000001):
        power_iteration(prob, n)
    else:
        print("Power iteration method does not converge for this matrix!")

In [6]:
def sortByPageRank(filename, alpha, teleport):
    """
    ### Description:
    This is the driver function, which would be calling all the required functions.

    ### Args:
    `filename` : The name of the file which contains the input.

    `alpha` : probability of teleportation if its allowed.

    `teleport` : Whether to run the PageRank algorithm with teleportation allowed or not.

    ### Returns:
    Doesn't returns anything.
    """
    arr, n = takeInput(filename)
    print(arr)
    prob = createProbabilityMatrix(arr, n, alpha, teleport)
    rankAndSort(prob, n)

In [7]:
sortByPageRank('input.txt', alpha=0.5, teleport=True)

[[0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 1.]
 [0. 1. 1. 0.]]
PageRank scores using linear algebra packages:  [0.17142857 0.37142857 0.22857143 0.22857143]
Descending order of nodes by PageRank:
[2 4 3 1]
PageRank scores using power iteration:  [[0.17142857 0.37142857 0.22857143 0.22857143]]
Descending order of nodes by PageRank:
[2 4 3 1]
